service: f1tof12-server

provider:
  name: aws
  runtime: python3.12
  region: ap-south-1
  environment:
    S3_BUCKET: f1tof12-db-backup-mumbai
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource: "arn:aws:s3:::f1tof12-db-backup-mumbai/*"

functions:
  api:
    handler: lambda_handler.handler
    events:
      - httpApi: '*'
    timeout: 30

plugins:
  - serverless-python-requirements