AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

# CloudFront secret fetched at runtime from SSM

Globals:
  Function:
    Timeout: 30
    Runtime: python3.12
  HttpApi:
    DefaultRouteSettings:
      ThrottlingRateLimit: 1000
      ThrottlingBurstLimit: 2000
    CorsConfiguration:
      AllowOrigins:
        - "http://localhost:3000"
        - "https://f1tof12.com"
        - "https://sz8wal44w0.execute-api.ap-south-1.amazonaws.com"
      AllowHeaders:
        - "Content-Type"
        - "Authorization"
        - "x-origin"
        - "x-cloudfront-secret"
      AllowMethods:
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"

Resources:
  F1toF12LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/f1tof12-api-logs
      RetentionInDays: 14

  F1toF12API:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_handler.handler
      LoggingConfig:
        LogGroup: !Ref F1toF12LogGroup
      Environment:
        Variables:
          ENVIRONMENT: prod
          CUSTOMER: vst
          # Cognito config fetched at runtime from us-east-1
          # CloudFront secret fetched at runtime from SSM
          USE_DYNAMODB: true
          USERS_TABLE: f1tof12-users
          COMPANIES_TABLE: f1tof12-companies
          SPOCS_TABLE: f1tof12-spocs
          INVOICES_TABLE: f1tof12-invoices
          COUNTERS_TABLE: f1tof12-counters
          REQUIREMENTS_TABLE: f1tof12-requirements
          PROCESS_PROFILES_TABLE: f1tof12-process-profiles
          PROFILES_TABLE: f1tof12-profiles
          REQUIREMENT_STATUSES_TABLE: f1tof12-requirement-statuses
          PROFILE_STATUSES_TABLE: f1tof12-profile-statuses
      Policies:
        - Version: "2012-10-17"
          Statement:

            - Effect: Allow
              Action:
                - cognito-idp:GetUser
                - cognito-idp:ListUsers
                - cognito-idp:InitiateAuth
                - cognito-idp:RespondToAuthChallenge
                - cognito-idp:GlobalSignOut
                - cognito-idp:AdminGetUser
                - cognito-idp:AdminUpdateUserAttributes
                - cognito-idp:AdminResetUserPassword
                - cognito-idp:AdminConfirmSignUp
                - cognito-idp:AdminEnableUser
                - cognito-idp:AdminDisableUser
                - cognito-idp:AdminCreateUser
                - cognito-idp:AdminSetUserPassword
              Resource: "*"
            - Effect: Allow
              Action:
                - ssm:GetParameter
                - ssm:GetParameters
              Resource: 
                - "arn:aws:ssm:us-east-1:*:parameter/f1tof12/*"
                - "arn:aws:ssm:ap-south-1:*:parameter/f1tof12/*"
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Scan
                - dynamodb:Query
              Resource:
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/f1tof12-users"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/f1tof12-companies"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/f1tof12-spocs"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/f1tof12-invoices"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/f1tof12-counters"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/f1tof12-requirements"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/f1tof12-process-profiles"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/f1tof12-profiles"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/f1tof12-requirement-statuses"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/f1tof12-profile-statuses"
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
        RootEvent:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY

  ThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: F1toF12-API-Throttling
      AlarmDescription: Alert when API Gateway throttling occurs
      MetricName: 4XXError
      Namespace: AWS/ApiGatewayV2
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiId
          Value: !Ref ServerlessHttpApi

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"

