AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  CognitoUserPoolId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /f1tof12/cognito/user-pool-id
  CognitoClientId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /f1tof12/cognito/client-id

Globals:
  Function:
    Timeout: 30
    Runtime: python3.12
  HttpApi:
    CorsConfiguration:
      AllowOrigins:
        - "http://localhost:3000"
        - "https://f1tof12.com"
        - "https://zhijjc4ru2.execute-api.ap-south-1.amazonaws.com/"
      AllowHeaders:
        - "Content-Type"
        - "Authorization"
      AllowMethods:
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"

Resources:
  F1toF12API:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_handler.handler
      Environment:
        Variables:
          S3_BUCKET: f1tof12-db-backup
          COGNITO_USER_POOL_ID: !Ref CognitoUserPoolId
          COGNITO_CLIENT_ID: !Ref CognitoClientId
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:DeleteObject
              Resource: "arn:aws:s3:::f1tof12-db-backup/*"
            - Effect: Allow
              Action:
                - s3:ListBucket
              Resource: "arn:aws:s3:::f1tof12-db-backup"
            - Effect: Allow
              Action:
                - cognito-idp:GetUser
                - cognito-idp:ListUsers
              Resource: "*"
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: "arn:aws:ssm:ap-south-1:*:parameter/f1tof12/cognito/*"
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
        RootEvent:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"